[build]
  command = "npm install --legacy-peer-deps && npm install prisma autoprefixer && npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.2"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["@prisma/client"]
  node_bundler = "esbuild"
  environment = { NEXT_TELEMETRY_DISABLED = "1", NODE_ENV = "production" } 